services:
  nginx-proxy:
    image: "pug9483/chelsea-fe:latest"
    container_name: "my-nginx-proxy"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-app
    networks:
      - my_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot

  spring-app:
    image: "pug9483/chelsea-be:latest"
    container_name: "my-spring-container"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
      - redis
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    networks:
      - my_network

  mysql:
    image: "mysql:8.0"
    container_name: "my-mysql-db"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  redis:
    image: "redis:alpine"
    container_name: "my-redis-cache"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - my_network

  mongo:
    image: "mongo:6.0"
    container_name: "my-mongo-db"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  jenkins:
    build: . 
    container_name: "my-jenkins"
    restart: always
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - /home/ubuntu/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/app:/app
    networks:
      - my_network
    environment:
      - TZ=Asia/Seoul 

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  mongodb_data:
