services:
  ai-app:
    build: ./AI
    container_name: local-ai-app-standalone
    restart: always
    ports:
      - "9000:9000" #임시로 9000번 포트를 쓰고있어요
    env_file:
      - ./AI/.env
    networks:
      - chelsea_default

networks:
  chelsea_default:
    external: true
