export { default as MainTag } from "./MainTag"
export { default as MajorTag } from "./MajorTag"
export { default as NormalTag } from "./NormalTag"
export { default as PositionTag } from "./PositionTag"
export { default as SearchBar } from "./SearchBar"
export { default as WhiteTag } from "./WhiteTag"
