spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQL_CONTAINER_NAME}:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin

logging:
  level:
    com.sonfind.chelsea: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

server:
  port: 8090
